# Generated by Django 4.1 on 2022-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.IntegerField(default=3, max_length=1),
        ),
    ]
