# Generated by Django 4.1 on 2022-09-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_users_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.IntegerField(default=3),
        ),
    ]
