# Generated by Django 4.1 on 2022-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addInstitute',
            fields=[
                ('instituteId', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('instituteName', models.TextField(blank=True, max_length=50)),
                ('instituteAddress', models.TextField(max_length=50)),
            ],
        ),
    ]
