# Generated by Django 4.1 on 2022-09-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteID', models.IntegerField(unique=True)),
                ('instituteName', models.TextField(blank=True, max_length=50)),
                ('instituteAddress', models.TextField(max_length=150)),
            ],
        ),
    ]
