# Generated by Django 4.1 on 2022-09-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField(unique=True)),
                ('courseName', models.TextField(blank=True, max_length=50)),
                ('type', models.IntegerField(default=3)),
                ('InstituteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.institute')),
            ],
        ),
    ]
