# Generated by Django 4.1 on 2022-09-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='InstituteID',
            new_name='instituteID',
        ),
    ]
