# Generated by Django 4.1 on 2022-10-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='superadmin.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField(blank=True, max_length=40)),
                ('credits', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester1', to='administrator.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchID', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.TextField(blank=True, max_length=50)),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='superadmin.course')),
            ],
        ),
    ]
