# Generated by Django 4.1 on 2022-10-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolment',
            field=models.BigIntegerField(blank=True),
        ),
    ]
