# Generated by Django 4.1 on 2022-09-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='superadmin.course')),
            ],
        ),
    ]
