# Generated by Django 4.1 on 2022-09-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('administrator', '0002_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='courseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='superadmin.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='courseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='superadmin.course'),
        ),
    ]
