# Generated by Django 4.1 on 2022-09-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_batch_coursename_alter_semester_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField(blank=True, max_length=40)),
                ('credits', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester1', to='administrator.semester')),
            ],
        ),
    ]
